[tool.isort]
profile = "google"
line_length = 120
# multi_line_output = 3 means "Vertical Hanging Indent"
multi_line_output = 3
# include_trailing_comma = true adds a comma at the end (makes diffs cleaner)
include_trailing_comma = true
# force_grid_wrap = 0 means "only wrap if it exceeds line length"
# If you want to FORCE wrapping even for short imports, change this to 1 or 2.
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
src_paths = ["backend"]

[tool.yapf]
based_on_style = "google"
column_limit = 120
indent_width = 4
# check them
split_before_first_argument = false
dedent_closing_brackets = true
coalesce_brackets = true

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
files = "backend/src"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "-v"
log_cli = true 
# log_cli_level = DEBUG
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
